import { Mic, Upload, Zap, Bell, Shield, SlidersHorizontal, Crosshair, MessageSquare, Radio } from 'lucide-react';
import { motion } from 'framer-motion';
import NeonCard from '../components/NeonCard';
import GlassCard from '../components/GlassCard';
import AIStatusCard from '../components/AIStatusCard';
import AnimatedStatCard from '../components/AnimatedStatCard';
import TreatmentTimeline from '../components/TreatmentTimeline';
import AnalyticsChartCard from '../components/AnalyticsChartCard';
import AIAnalysisPanel from '../components/AIAnalysisPanel';
import { aiTrend, analyticsBars, homeStats, telemetry } from '../utils/mockData';
import { floatLoop } from '../animations/motionVariants';
import { useLiveMetric } from '../hooks/useLiveMetric';

export function HomeScreen() {
  const latency = useLiveMetric(23, 4);
  return <div className="space-y-4"><NeonCard><p className="text-xs text-neon">ONCOBEAM AI</p><h1 className="mt-1 text-2xl font-semibold font-heading">Good evening, Doctor.</h1><p className="text-sm text-white/65">Radiation command center synchronized.</p><motion.div {...floatLoop} className="mt-3 inline-flex items-center gap-2 rounded-full bg-success/15 px-3 py-1 text-xs text-success"><span className="h-2 w-2 rounded-full bg-success" /> Live telemetry stable</motion.div></NeonCard><AIStatusCard latency={latency} /><div className="grid grid-cols-2 gap-3">{homeStats.map((item) => <AnimatedStatCard key={item.label} {...item} />)}</div><GlassCard><p className="mb-2 text-sm">Radiation workflow summary</p><div className="flex h-20 items-end gap-1">{telemetry.map((v, i) => <div key={i} className="w-full rounded-t bg-gradient-to-t from-purple/80 to-neon" style={{ height: `${v}%` }} />)}</div></GlassCard></div>;
}

export function AssistScreen() {
  return <div className="space-y-3.5"><AIAnalysisPanel /><GlassCard><p className="mb-2 text-sm font-semibold">Patient Analysis Snapshot</p><div className="grid grid-cols-2 gap-2 text-xs">{[['Patient ID', 'ONC-4471'], ['Cancer Type', 'NSCLC'], ['Radiation Stage', 'IIIA'], ['Current Fraction', '18 / 30'], ['AI Confidence', '98.9%'], ['Treatment Progress', '60%']].map(([k, v]) => <div key={k} className="rounded-xl border border-white/10 bg-white/5 p-2"><p className="text-white/60">{k}</p><p className="mt-1 font-semibold text-neon">{v}</p></div>)}</div></GlassCard><div className="grid gap-3"><GlassCard><div className="mb-2 flex items-center justify-between"><p className="font-semibold">3D Body Target Preview</p><Crosshair className="h-4 w-4 text-neon" /></div><div className="relative h-36 overflow-hidden rounded-2xl border border-neon/25 bg-gradient-to-b from-white/5 to-neon/10"><div className="absolute inset-0 scanner-grid opacity-30" /><div className="absolute left-1/2 top-1/2 h-28 w-14 -translate-x-1/2 -translate-y-1/2 rounded-[999px] border border-white/30" /><div className="absolute left-1/2 top-[44%] h-4 w-4 -translate-x-1/2 rounded-full bg-danger shadow-[0_0_16px_rgba(255,71,126,1)] tumor-ping" /><div className="absolute left-[10%] top-[56%] h-0.5 w-[80%] bg-gradient-to-r from-transparent via-neon to-transparent beam-line" /></div></GlassCard><GlassCard><p className="mb-2 font-semibold">Voice AI Expansion</p><div className="rounded-xl border border-purple/30 bg-purple/10 p-3"><div className="mb-2 flex items-center justify-between text-xs text-white/70"><span className="flex items-center gap-1"><Radio className="h-3.5 w-3.5 text-neon" />Listening Mode</span><span className="text-neon">Live</span></div><div className="voice-wave mb-3 h-10 rounded-lg bg-white/5" /><div className="flex items-center justify-between"><div className="space-y-1 text-xs text-white/70"><p className="flex items-center gap-1"><MessageSquare className="h-3.5 w-3.5 text-neon" />"Recommend adaptive plan"</p><p>AI: "Suggested beam arc narrowed by 6%."</p></div><button className="relative rounded-full bg-purple/25 p-3 text-purple"><span className="absolute inset-0 rounded-full voice-ripple" /><Mic className="relative z-10 h-4 w-4" /></button></div></div></GlassCard></div><GlassCard><button className="flex w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-neon/35 p-4 text-neon"><Upload className="h-4 w-4" />Upload CT Scan Set</button></GlassCard></div>;
}

export const TreatmentScreen = () => <div className="space-y-4"><NeonCard><p className="mb-3 text-sm">Treatment timeline</p><TreatmentTimeline /></NeonCard><div className="grid grid-cols-2 gap-3"><GlassCard><p className="text-xs text-white/60">Progress</p><p className="mt-1 text-2xl text-success">18 / 30</p></GlassCard><GlassCard><p className="text-xs text-white/60">LINAC #4</p><p className="mt-1 text-2xl text-neon">Active</p></GlassCard></div><GlassCard><p className="text-sm">Beam planning</p><div className="mt-2 h-24 rounded-2xl bg-gradient-to-r from-purple/30 to-neon/30" /></GlassCard></div>;

export const AnalyticsScreen = () => <div className="space-y-4"><AnalyticsChartCard title="Cancer Distribution" values={analyticsBars} /><AnalyticsChartCard title="AI Performance Trend" values={aiTrend} /><AnalyticsChartCard title="Machine Usage" values={[88, 83, 72, 92, 64, 78, 90]} /></div>;

export const ProfileScreen = () => <div className="space-y-3"><NeonCard><p className="text-lg font-semibold">Dr. Aria Morgan</p><p className="text-sm text-white/60">Lead Radiation Oncologist</p></NeonCard>{[[Bell, 'Notifications'], [Shield, 'Security'], [SlidersHorizontal, 'AI Configuration'], [Zap, 'Dark Mode']].map(([Icon, label]) => <GlassCard key={label} className="flex items-center justify-between"><span className="flex items-center gap-2"><Icon className="h-4 w-4 text-neon" />{label}</span><span className="text-xs text-white/45">Manage</span></GlassCard>)}<GlassCard><p className="text-sm">OncoBeam AI v2.8 • Cyber oncology assistant.</p></GlassCard></div>;
